app = "zhorten"
primary_region = "ord"

[env]
  ZHORTEN_ADDR = "0.0.0.0:3000"
  ZHORTEN_DB = "/data/zhorten.db"
  ZHORTEN_SITE_ROOT = "/app/site"
  ZHORTEN_SECURE_COOKIES = "true"

[[mounts]]
  source = "zhorten_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
