[package]
name = "zhorten-sqlite"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
rusqlite = { version = "0.37.0", features = ["bundled"] }
url = "2.5.8"
zhorten-core.workspace = true
zhorten-service.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
tokio = { version = "1.53.1", features = ["macros", "rt"] }
